export { GameHistory } from "./components/history/GameHistory";
export { GameLoading } from "./components/loading/GameLoading";
export { GamePlay } from "./components/play/GamePlay";
export { GameResult } from "./components/result/GameResult";
export { GameSettings } from "./components/settings/GameSettings";
export { GAME_ACTIONS } from "./constants/game-actions";
export { gameReducer, initialGameState } from "./model/game-reducer";
export { readingTasks } from "./model/reading-tasks";
export type { ReadingTask } from "./types/reading";
export type { GameSettingsState } from "./types/setting";
